// tailwind.config.ts
import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        Grenoble: ["var(--font-Grenoble)"],
        Helvetica: ["var(--font-Helvetica)"],
        MaronRose: ["var(--font-MaronRose)"],
        Hatton_Bold: ["var(--font-Hatton_Bold)"],
        LobsterTwo_Bold: ["var(--font-LobsterTwo_Bold)"],
        Helvetica_Rounded: ["var(--font-Helvetica_Rounded)"],
        Brittany_Signature: ["var(--font-Brittany_Signature)"],
        Lora_Bold: ["var(--font-Lora_Bold)"],
        Lora_BoldItalic: ["var(--font-Lora_BoldItalic)"],
        Lora_Italic: ["var(--font-Lora_Italic)"],
        Lora_Medium: ["var(--font-Lora_Medium)"],
        Lora_MediumItalic: ["var(--font-Lora_MediumItalic)"],
        Lora_Regular: ["var(--font-Lora_Regular)"],
        Lora_SemiBold: ["var(--font-Lora_SemiBold)"],
        Lora_SemiBoldItalic: ["var(--font-Lora_SemiBoldItalic)"],
      },
      backgroundImage: {},
    },
  },
  plugins: [
    require("daisyui"),
    require("preline/plugin"),
    require("flowbite/plugin"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("tailwind-scrollbar-hide"),
    require("tailwind-scrollbar")({ nocompatible: true }),
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};

export default config;
