// app/_others/initialCategories.ts
import { Category } from "../types/cart";

const initialCategories: Category[] = [
  {
    image: "/Food.jpg",
    title: "All",
    active: true,
    items: [],
  },
  {
    image: "/biryani/Biryani_Special.jpg",
    title: "Biryani",
    active: false,
    items: [
      {
        title: "Biryani Special",
        description: "Delicious and spicy biryani with aromatic herbs and flavorful spices.",
        image: "/biryani/Biryani_Special.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.5,
      },
      {
        title: "Herbal Biryani",
        description: "Aromatic biryani cooked with fresh herbs and tender meat pieces.",
        image: "/biryani/Herbal_Biryani.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.3,
      },
      {
        title: "Chicken Biryani",
        description:
          "Flavorful chicken biryani cooked to perfection with rich spices and fragrant rice.",
        image: "/biryani/Chicken_Biryani.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.7,
      },
      {
        title: "Vegetable Biryani",
        description: "Vegetarian biryani with assorted vegetables and aromatic basmati rice.",
        image: "/biryani/Vegetable_Biryani.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "veg",
        rating: 4.2,
      },
    ],
  },
  {
    image: "/kebab/Grilled_Kebab.jpg",
    title: "Kebab",
    active: false,
    items: [
      {
        title: "Grilled Kebab",
        description: "Juicy and tender grilled kebab marinated in special spices and herbs.",
        image: "/kebab/Grilled_Kebab.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.6,
      },
      {
        title: "Spicy Mutton Kebab",
        description: "Spicy mutton kebab with a perfect blend of spices and tender meat.",
        image: "/kebab/Spicy_Mutton_Kebab.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.8,
      },
      {
        title: "Chicken Kebab",
        description: "Tender chicken kebab grilled to perfection and marinated in spicy sauce.",
        image: "/kebab/Chicken_Kebab.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.5,
      },
      {
        title: "Chickpea Kebab",
        description:
          "Vegetarian kebab made with chickpeas and exotic spices for a delightful taste.",
        image: "/kebab/Chickpea_Kebab.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
    ],
  },
  {
    image: "/noodles/Veggie_Noodles.jpg",
    title: "Noodles",
    active: false,
    items: [
      {
        title: "Veggie Noodles",
        description: "Stir-fried noodles with assorted vegetables and savory soy sauce.",
        image: "/noodles/Veggie_Noodles.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
      {
        title: "Spicy Chicken Noodles",
        description: "Spicy chicken noodles tossed with fresh vegetables and spicy seasoning.",
        image: "/noodles/Spicy_Chicken_Noodles.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.3,
      },
      {
        title: "Soy Sauce Noodles",
        description: "Noodles stir-fried with soy sauce and a hint of garlic for added flavor.",
        image: "/noodles/Soy_Sauce_Noodles.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
      {
        title: "Garlic Shrimp Noodles",
        description: "Garlic-infused noodles with succulent shrimp and aromatic herbs.",
        image: "/noodles/Garlic_Shrimp_Noodles.jpg",
        price: { small: "50", medium: "75", full: "100" },
        forTwo: 200,
        genre: "non-veg",
        rating: 4.3,
      },
    ],
  },
  {
    image: "/drinks/Iced_Tea.jpg",
    title: "Drinks",
    active: false,
    items: [
      {
        title: "Iced Tea",
        description: "Refreshing iced tea with lemon slices and mint leaves.",
        image: "/drinks/Iced_Tea.jpg",
        price: { small: "30", medium: "45", full: "60" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
      {
        title: "Cold Coffee",
        description: "Chilled coffee with milk and a hint of vanilla for a delightful taste.",
        image: "/drinks/Cold_Coffee.jpg",
        price: { small: "40", medium: "60", full: "80" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
      {
        title: "Hot Chocolate",
        description: "Creamy hot chocolate topped with whipped cream and chocolate shavings.",
        image: "/drinks/Hot_Chocolate.jpg",
        price: { small: "45", medium: "65", full: "90" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
      {
        title: "Fresh Fruit Juice",
        description: "Freshly squeezed fruit juice made from seasonal fruits.",
        image: "/drinks/Fresh_Fruit_Juice.jpg",
        price: { small: "35", medium: "50", full: "70" },
        forTwo: 200,
        genre: "veg",
        rating: 4.3,
      },
    ],
  },
];

export default initialCategories;
